language: scala
scala:
- 2.12.6
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/

addons:
  apt:
    packages:
    - oracle-java8-installer

before_install:
- sudo update-java-alternatives -s java-8-oracle
- export JAVA_HOME=/usr/lib/jvm/java-8-oracle
- java -version
- sudo rm -rf /var/lib/cassandra/*
- wget http://www.us.apache.org/dist/cassandra/3.3/apache-cassandra-3.3-bin.tar.gz && tar -xvzf apache-cassandra-3.3-bin.tar.gz
- sudo sh ./apache-cassandra-3.3/bin/cassandra -R
- sleep 20
