language: scala
scala:
  - 2.12.6
jdk: oraclejdk8

sudo: false
services:
  - docker

# default script for jobs, that do not have any specified
script:
  - docker-compose up
  - sbt test

after_failure:
  - docker-compose logs

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/
