# For detailed information about docker-compose visit https://docs.docker.com/compose/
# To start a simple configuration of the smack stack in the local machine run:
# docker-compose -f docker-compose.yml -f docker-compose.testing.yml up -d

version: '2.1'
services:
  kafka:
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka

  seed:
    image: eciavatta/smack-template:latest
    command: -l INFO -a seed:5000 seed
    environment:
      HOST: seed
      PORT_REMOTE: 5000
      PORT_BIND_REMOTE: 5000

  migrate:
    image: eciavatta/smack-template:latest
    command: migrate --create-keyspace -l INFO -c cassandra:9042
    depends_on:
      cassandra:
        condition: service_healthy

  frontend:
    image: eciavatta/smack-template:latest
    command: -d false -l INFO -a seed:5000 frontend
    depends_on:
      seed:
        condition: service_started
    environment:
      HOST: frontend
      PORT_REMOTE: 5001
      PORT_BIND_REMOTE: 5001
      PORT_HTTP: 8080
    ports:
      - "8080:8080"

  backend:
    image: eciavatta/smack-template:latest
    command: -l INFO -a seed:5000 -c cassandra:9042 -k kafka:9092 backend
    depends_on:
      cassandra:
        condition: service_healthy
      kafka:
        condition: service_healthy
      seed:
        condition: service_started
      migrate:
        condition: service_started
    environment:
      HOST: backend
      PORT_REMOTE: 5002
      PORT_BIND_REMOTE: 5002

  service:
    image: eciavatta/smack-template:latest
    command: -l INFO -a seed:5000 -c cassandra:9042 -k kafka:9092 service
    depends_on:
      cassandra:
        condition: service_healthy
      kafka:
        condition: service_healthy
      seed:
        condition: service_started
      migrate:
        condition: service_started
    environment:
      HOST: service
      PORT_REMOTE: 5003
      PORT_BIND_REMOTE: 5003
