#!/usr/bin/env bash

if [ $# -ne 1 ] && [ "$1" != "up" ] && [ "$1" != "down" ]; then
  echo "Invalid arguments. Usage: $0 [up|down]"
  exit 1
fi

if [ "$1" == "up" ]; then

  ./cluster-init-compose up
  ./cluster-smack-compose up

fi

if [ "$1" == "down" ]; then
  
  ./cluster-smack-compose down
  ./cluster-init-compose down

fi
