#!/usr/bin/env bash

# Find the java binary
if [ -n "${JAVA_HOME}" ]; then
  RUNNER="${JAVA_HOME}/bin/java"
else
  if [ "$(command -v java)" ]; then
    RUNNER="java"
  else
    echo "JAVA_HOME is not set" >&2
    exit 1
  fi
fi

# Find the package and the main
APP_PATH=/app/
if [ "$1" == "client" ]; then
  LAUNCH_JAR="${APP_PATH}smack-client-$VERSION.jar"
  LAUNCH_MAIN=smack.entrypoints.ClientMain
  ARGS="${@:2}"
elif [ "$1" == "migrate" ]; then
  LAUNCH_JAR="${APP_PATH}smack-migrate-$VERSION.jar"
  LAUNCH_MAIN=smack.entrypoints.MigrateMain
  ARGS="${@:2}"
elif [ "$1" == "analysis" ]; then
  LAUNCH_JAR="${APP_PATH}smack-analysis-$VERSION.jar"
  LAUNCH_MAIN=smack.entrypoints.AnalysisMain
  ARGS="${@:2}"
else
  LAUNCH_JAR="${APP_PATH}smack-template-$VERSION.jar"
  LAUNCH_MAIN=smack.entrypoints.Main
  ARGS="$@"
fi

if [ ! -z "$JAVA_AGENTS" ]; then
  JAVA_OPT_AGENTS="-javaagent:$JAVA_AGENTS"
else
  JAVA_OPT_AGENTS=""
fi

# Execute the command
$RUNNER -Xmx128m $JAVA_OPT_AGENTS -cp $LAUNCH_JAR $LAUNCH_MAIN $ARGS
